# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 03:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_asiento', models.CharField(max_length=60)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Asientos',
                'verbose_name': 'Asiento',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('codigo', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=60)),
                ('celular', models.CharField(max_length=60, null=True)),
                ('email', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Clientes',
                'verbose_name': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_destino', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'verbose_name_plural': 'Destinos',
                'verbose_name': 'Destino',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateField()),
                ('hora_salida', models.TimeField()),
                ('descripcion_horario', models.CharField(blank=True, max_length=20)),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reserva.Destino')),
            ],
            options={
                'verbose_name_plural': 'Horarios',
                'verbose_name': 'Horario',
            },
        ),
        migrations.CreateModel(
            name='Origen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_origen', models.CharField(max_length=60)),
                ('descripcion', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'Origens',
                'verbose_name': 'Origen',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle_pago', models.CharField(max_length=60)),
                ('codigo', models.CharField(max_length=50)),
                ('monto', models.FloatField(blank=True, null=True)),
                ('sub_total', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Pagos',
                'verbose_name': 'Pago',
            },
        ),
        migrations.AddField(
            model_name='reserva',
            name='costo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_reserva',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reserva.Origen'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reserva.Reserva'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='asiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reserva.Asiento'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='horario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reserva.Horario'),
        ),
    ]
